# -*- coding: utf-8 -*-
"""naive bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m91xtD6tb2gxEO9zK8NpSOvPl5vwclJ6
"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import warnings

# Suppress SettingWithCopyWarning by importing it from the correct location (pd.errors)
warnings.filterwarnings('ignore', category=pd.errors.SettingWithCopyWarning)

# --- Data Loading and Preparation ---
df = pd.read_csv("spam.csv", encoding='latin-1')

# Select the relevant columns (v1 for label, v2 for text)
df = df.iloc[:, [0, 1]]
df.columns = ['label', 'message']

# Define the features (X) and target (y)
X = df['message']
y = df['label']

print("--- Data Loaded and Prepared ---")
print(f"Total messages: {len(X)}")
print(f"Labels: {y.unique()}")
print("------------------------------")

# --- Feature Extraction and Model Training ---

# 1. Initialize the CountVectorizer
cv = CountVectorizer()

# 2. Fit and Transform the text data (X) to create the feature matrix
X_vec = cv.fit_transform(X)

# 3. Train the Naive Bayes Model
model = MultinomialNB()
model.fit(X_vec, y)

print("✅ Model Training Complete using Multinomial Naive Bayes.")

# --- User Input and Prediction ---

# 4. Take User Input for the New Sample
user_input = input("\nEnter a message to classify (e.g., 'Claim your free prize now!'):\n> ")

# Prepare the input for the model
test_message = [user_input]

# Transform the new message using the FITTED vectorizer
# This converts the user's text into the numerical format the model understands.
test_vec = cv.transform(test_message)

# Predict the label for the transformed test data
prediction = model.predict(test_vec)

# Output the result
print("\n--- Classification Result ---")
print(f"Message Entered: '{user_input}'")
# The prediction will be 'ham' or 'spam'
print(f"Model Prediction: This message is classified as **{prediction[0].upper()}**.")

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

# Load dataset
df = pd.read_csv("spam.csv", encoding='latin-1')
df = df.iloc[:, [0, 1]]
df.columns = ['label', 'message']

# Features & target
X = df['message']
y = df['label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Text vectorization
cv = CountVectorizer()
X_train_vec = cv.fit_transform(X_train)
X_test_vec = cv.transform(X_test)

# Model training
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Prediction
y_pred = model.predict(X_test_vec)

# Evaluation
print("\n--- Model Evaluation ---")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# User input
user_input = input("\nEnter a message to classify:\n> ")
test_vec = cv.transform([user_input])
prediction = model.predict(test_vec)

print("\n--- Result ---")
print(f"Message: {user_input}")
print(f"Prediction: {prediction[0].upper()}")